queries=["",
           "d.find()",
           "d.find({},{'restaurant_id':1,'name':True, 'borough':1, 'cuisine':1})",
           "d.find({},{'restaurant_id':1,'name':True, 'borough':1, 'cuisine':1, '_id':0})",
           "d.find({},{'restaurant_id':1,'name':1, 'borough':1, 'address.zipcode':1, '_id':0})",
           "d.find({'borough':'Bronx'})",
           "d.find({'borough':'Bronx'}).limit(5)",
           "d.find({'borough':'Bronx'}).skip(5).limit(5)",
           "d.find({'grades.score':{'$gt':90}})",
           "d.find({'grades':{'$elemMatch':{'score':{'$gt':80,'$lt':100}}}})",
           "d.find({'address.coord':{'$lt':-95.754168}})",
           "d.find( {'$and': [ {'cuisine':{'$ne':'American '}}, {'grades.score':{'$gt':70}}, {'address.coord':{'$lt': -65.754168}} ] } )",
           "d.find( { 'cuisine':{'$ne':'American '}, 'grades.score':{'$gt':70}, 'address.coord':{'$lt':-65.754168} })",
           "d.find( { 'cuisine':{'$ne':'American '}, 'grades.grade':'A', 'borough':{'$ne':'Brooklyn'} }).sort('cuisine',-1)",
           "d.find({'name':re.compile('^Wil')},{'restaurant_id':1,'name':1,'borough':1,'cuisine':1})",
           "d.find({'name':re.compile('ces$')},{'restaurant_id':1,'name':1,'borough':1,'cuisine':1})",
           "d.find({'name':re.compile('.*Reg.*')},{'restaurant_id':1,'name':1,'borough':1,'cuisine':1})",
           "d.find( { 'borough':'Bronx', 'cuisine':{'$in':['American ','Chinese']} } )",
           "d.find( { 'borough':{'$in':['Staten Island','Queens','Bronx','Brooklyn']} }, {'restaurant_id':1,'name':1,'borough':1,'cuisine':1} )",
           "d.find( { 'borough':{'$nin':['Staten Island','Queens','Bronx','Brooklyn']} }, {'restaurant_id':1,'name':1,'borough':1,'cuisine':1} )",
           "d.find( {'grades.score':{'$lt':11}}, {'restaurant_id':1,'name':1,'borough':1,'cuisine':1} )",
           "d.find( {'$or':[{'cuisine':{'$nin':['American ','Chinese']}},{'name':re.compile('^Wil')}]}, {'restaurant_id':1,'name':1,'borough':1,'cuisine':1} )",
           "d.find({'grades.grade':'A','grades.score':11,'grades.date':datetime.datetime(2014,8,11,0,0,0)},{'restaurant_id':1,'name':1,'grades':1})",
           "d.find( {'grades.1.date':datetime.datetime(2014,8,11,0,0,0),'grades.1.grade':'A','grades.1.score':9}, {'restaurant_id':1,'grades':1,'name':1} )",
           "d.find( {'address.coord.1':{'$gt':42,'$lte':52}},{'restaurant_id':1,'name':1,'address.coord':1})",
           "d.find().sort('name',ASCENDING)",
           "d.find().sort('name',-1)",
           "d.find().sort([('name',1),('borough',DESCENDING)])",
           "d.find({'address':{'$exists':True}})",
           "d.find({'address.coord':{'$type':1}})",
           "d.find({'grades.score':{'$mod':[7,0]}},{'restaurant_id':1,'name':1,'grades':1})",
           "d.find({'name':re.compile('.*mon.*',re.IGNORECASE)},{'name':1,'borough':1,'address.coord':1,'cuisine':1})",
           "d.find({'name':re.compile('^Mad', re.IGNORECASE)},{'name':1,'borough':1,'address.coord':1,'cuisine':1})"]


